export const APP_NAME = "BD Lead Engine";

export const DEFAULT_SCAN = {
  limitPerQuery: 8,
  maxQueries: 24,
  fetchPages: true,
  deepEnrich: false,
  searchContacts: true,
  queryOffset: 0,
  includePartners: true,
  includeRecruitment: true,
  includeIntentPosts: true,
  includeEcosystem: true,
  includeSocialProfiles: true,
  includeForums: true,
  includeSpecialistSources: true,
  includeYouTube: false,
  regionSet: "global"
};

export const SEARCH_PROFILES = {
  global: {
    label: "Global PT/ES/EN",
    regions: [
      "Brazil",
      "Brasil",
      "Mexico",
      "Colombia",
      "Chile",
      "Argentina",
      "Peru",
      "Portugal",
      "Spain",
      "LatAm",
      "Latin America",
      "UAE",
      "Dubai",
      "South Africa",
      "United Kingdom"
    ],
    languages: ["Portuguese", "Spanish", "English"]
  },
  latam: {
    label: "LatAm + Brazil",
    regions: [
      "Brazil",
      "Brasil",
      "Mexico",
      "Colombia",
      "Chile",
      "Argentina",
      "Peru",
      "Ecuador",
      "Uruguay",
      "Paraguay",
      "Bolivia",
      "Panama",
      "Costa Rica",
      "Dominican Republic",
      "LatAm",
      "Latin America"
    ],
    languages: ["Portuguese", "Spanish", "English"]
  },
  english: {
    label: "English speaking",
    regions: [
      "United Kingdom",
      "UAE",
      "Dubai",
      "South Africa",
      "Nigeria",
      "Kenya",
      "India",
      "Singapore",
      "Australia"
    ],
    languages: ["English"]
  }
};

export const PARTNER_QUERY_TEMPLATES = [
  "site:linkedin.com/in \"introducing broker\" \"forex\" {region}",
  "site:linkedin.com/in \"forex affiliate\" {region}",
  "site:linkedin.com/in \"trading educator\" \"forex\" {region}",
  "\"forex\" \"introducing broker\" {region}",
  "\"forex\" \"IB\" \"partner\" {region}",
  "\"forex affiliate\" {region}",
  "\"CFD broker\" \"affiliate\" {region}",
  "\"trading academy\" \"forex\" {region}",
  "\"forex educator\" {region}",
  "\"forex signals\" \"community\" {region}",
  "\"copy trading\" \"forex\" {region}",
  "\"forex\" \"Telegram\" \"community\" {region}",
  "site:t.me \"forex\" {region}",
  "site:t.me \"trading\" \"forex\" {region}",
  "\"forex Telegram group\" {region}",
  "site:youtube.com \"forex\" \"trader\" {region}",
  "site:youtube.com \"forex trading\" \"channel\" {region}",
  "\"curso de forex\" {region}",
  "\"academia de trading\" \"forex\" {region}",
  "\"mentor forex\" {region}",
  "\"forex mentor\" {region}",
  "\"trading community\" \"forex\" {region}",
  "\"forex\" \"YouTube\" \"trader\" {region}",
  "\"forex\" \"Instagram\" \"trader\" {region}",
  "\"forex\" \"partnership\" \"broker\" {region}",
  "\"retail trading\" \"community\" {region}",
  "\"prop trading\" \"community\" {region}",
  "\"trading educator\" \"forex\" {region}",
  "\"forex\" \"whatsapp\" \"trading\" {region}",
  "\"forex\" \"discord\" \"trading\" {region}",
  "\"forex\" \"community\" \"whatsapp\" {region}",
  "\"forex\" \"copy trading\" \"telegram\" {region}",
  "\"forex\" \"signals\" \"whatsapp\" {region}",
  "\"forex\" \"affiliate\" \"whatsapp\" {region}",
  "\"forex\" \"educador\" \"instagram\" {region}",
  "\"forex\" \"trader\" \"instagram\" {region}",
  "\"trading\" \"forex\" \"linktree\" {region}",
  "\"trading\" \"forex\" \"beacons\" {region}",
  "\"trading\" \"forex\" \"contact\" {region}",
  "\"forex\" \"partnership\" \"contact\" {region}",
  "\"forex\" \"IB\" \"WhatsApp\" {region}",
  "site:linktr.ee \"forex\" \"trader\" {region}",
  "site:linktr.ee \"trading\" \"whatsapp\" {region}",
  "site:beacons.ai \"forex\" \"trader\" {region}",
  "site:bio.link \"forex\" \"trading\" {region}",
  "site:allmylinks.com \"forex\" \"trader\" {region}",
  "site:carrd.co \"forex\" \"trading\" {region}",
  "site:instagram.com \"forex trader\" \"whatsapp\" {region}",
  "site:instagram.com \"forex\" \"mentor\" {region}",
  "site:instagram.com \"forex\" \"signals\" {region}",
  "site:t.me \"forex signals\" {region}",
  "site:t.me \"forex community\" {region}",
  "site:tradingview.com/u/ \"forex\" {region}",
  "\"forex\" \"mentor\" \"whatsapp\" {region}",
  "\"forex\" \"sinais\" \"whatsapp\" Brasil",
  "\"forex\" \"senales\" \"whatsapp\" LatAm",
  "\"curso forex\" \"whatsapp\" {region}",
  "\"academia forex\" \"contato\" {region}",
  "\"comunidad forex\" \"whatsapp\" {region}",
  "\"forex\" \"book a call\" \"trading\" {region}",
  "\"forex\" \"contact me\" \"trader\" {region}",
  "\"forex\" \"partnerships\" \"telegram\" {region}",
  "\"forex\" \"affiliate\" \"telegram\" {region}",
  "\"forex\" \"copy trader\" \"contact\" {region}",
  "\"forex\" \"funded trader\" \"community\" {region}"
];

export const RECRUITMENT_QUERY_TEMPLATES = [
  "site:linkedin.com/in \"business development\" \"forex broker\" {region}",
  "site:linkedin.com/in \"partnership manager\" \"forex\" {region}",
  "site:linkedin.com/in \"affiliate manager\" \"forex\" {region}",
  "site:linkedin.com/in \"country manager\" \"forex broker\" {region}",
  "\"business development manager\" \"forex broker\" {region}",
  "\"partnership manager\" \"forex broker\" {region}",
  "\"affiliate manager\" \"forex broker\" {region}",
  "\"country manager\" \"forex broker\" {region}",
  "\"head of business development\" \"forex\" {region}",
  "\"regional manager\" \"broker\" \"forex\" {region}",
  "\"exness\" \"business development\" {region}",
  "\"XM\" \"affiliate manager\" {region}",
  "\"Octa\" \"business development\" {region}",
  "\"FBS\" \"partnership manager\" {region}",
  "\"HFM\" \"business development\" {region}",
  "\"Tickmill\" \"affiliate manager\" {region}",
  "\"IC Markets\" \"business development\" {region}",
  "\"Pepperstone\" \"partnerships\" {region}",
  "\"AvaTrade\" \"business development\" {region}",
  "\"Deriv\" \"affiliate manager\" {region}",
  "\"broker\" \"country manager\" \"LatAm\" \"forex\"",
  "\"forex broker\" \"Latin America\" \"partnerships\""
];

export const INTENT_POST_QUERY_TEMPLATES = [
  "site:linkedin.com/posts \"forex\" \"broker\" \"looking for\" {region}",
  "site:linkedin.com/posts \"forex\" \"which broker\" {region}",
  "site:linkedin.com/posts \"forex\" \"recommend broker\" {region}",
  "site:linkedin.com/posts \"forex\" \"best broker\" {region}",
  "site:linkedin.com/posts \"forex\" \"broker recommendation\" {region}",
  "site:linkedin.com/posts \"forex\" \"introducing broker\" {region}",
  "site:linkedin.com/posts \"forex\" \"IB\" \"partner\" {region}",
  "site:linkedin.com/posts \"forex\" \"affiliate\" \"broker\" {region}",
  "site:linkedin.com/posts \"CFD\" \"broker\" \"partner\" {region}",
  "site:linkedin.com/posts \"trading community\" \"broker\" {region}",
  "site:linkedin.com/feed/update \"forex\" \"broker\" \"looking for\" {region}",
  "site:linkedin.com/feed/update \"forex\" \"recommend broker\" {region}",
  "site:linkedin.com/in \"posts\" \"forex\" \"broker\" {region}",
  "site:linkedin.com/in \"forex\" \"open to partnerships\" {region}",
  "site:linkedin.com/in \"forex\" \"IB partner\" {region}",
  "site:linkedin.com/in \"forex\" \"introducing broker\" {region}",
  "\"procuro corretora\" forex",
  "\"procurando corretora\" forex",
  "\"qual corretora de forex\" Brasil trader",
  "\"melhor corretora\" forex Brasil trader",
  "\"corretora para forex\" Brasil trader",
  "\"corretora de forex\" \"comunidade\" Brasil",
  "\"busco broker\" forex",
  "\"buscando broker\" forex",
  "\"recomienden broker\" forex",
  "\"que broker recomiendan\" forex",
  "\"mejor broker\" forex LatAm",
  "\"broker para forex\" LatAm",
  "\"broker regulado\" forex \"partner\"",
  "\"looking for a forex broker\"",
  "\"looking for broker\" \"forex\" \"trader\"",
  "\"recommend a broker\" \"forex\"",
  "\"which broker do you use\" forex",
  "\"best broker for forex\" \"trading community\"",
  "\"need broker\" \"forex\" \"community\"",
  "\"forex broker\" \"open to partner\"",
  "\"forex broker\" \"partnership opportunity\"",
  "\"forex broker\" \"affiliate partner\"",
  "\"forex broker\" \"IB partner\"",
  "\"introducing broker\" \"looking for broker\"",
  "\"trading academy\" \"broker partnership\"",
  "\"forex signals\" \"broker partner\"",
  "\"trading community\" \"broker partner\"",
  "site:x.com \"looking for broker\" \"forex\"",
  "site:x.com \"recommend broker\" \"forex\"",
  "site:x.com \"forex\" \"IB partner\"",
  "site:reddit.com/r/Forex \"which broker\"",
  "site:reddit.com/r/Forex \"recommend broker\"",
  "site:tradingview.com \"forex\" \"broker\" \"message me\"",
  "site:tradingview.com/u/ \"forex\" \"signals\"",
  "site:facebook.com \"forex\" \"whatsapp\" \"broker\" {region}"
];

export const SOCIAL_QUERY_TEMPLATES = [
  "site:instagram.com \"forex trader\" \"whatsapp\" {region}",
  "site:x.com \"forex\" \"looking for broker\"",
  "site:linkedin.com/posts \"forex\" \"broker\" \"looking for\" {region}",
  "site:instagram.com \"forex signals\" \"whatsapp\" {region}",
  "site:x.com \"forex\" \"recommend broker\"",
  "site:linkedin.com/in \"introducing broker\" \"forex\" {region}",
  "site:instagram.com \"forex mentor\" \"whatsapp\" {region}",
  "site:twitter.com \"forex\" \"looking for broker\"",
  "site:facebook.com \"forex trading\" \"community\" \"whatsapp\" {region}",
  "site:tiktok.com \"forex trader\" {region}",
  "site:threads.net \"forex\" \"broker\"",
  "site:linktr.ee \"forex trader\" {region}",
  "site:linkedin.com/in \"forex trader\" \"{region}\"",
  "site:linkedin.com/in \"trading educator\" \"forex\" {region}",
  "site:linkedin.com/in \"introducing broker\" \"forex\" {region}",
  "site:linkedin.com/in \"forex\" \"open to partnerships\" {region}",
  "site:linkedin.com/in \"forex\" \"affiliate\" \"partner\" {region}",
  "site:linkedin.com/in \"forex\" \"community\" \"founder\" {region}",
  "site:linkedin.com/in \"trading academy\" \"founder\" {region}",
  "site:linkedin.com/in \"head of partnerships\" \"forex\" {region}",
  "site:linkedin.com/in \"business development\" \"forex broker\" {region}",
  "site:linkedin.com/company \"trading academy\" \"forex\" {region}",
  "site:linkedin.com/company \"forex\" \"education\" {region}",
  "site:linkedin.com/company \"forex\" \"community\" {region}",
  "site:linkedin.com/posts \"forex\" \"broker\" \"looking for\" {region}",
  "site:linkedin.com/posts \"forex\" \"recommend broker\" {region}",
  "site:linkedin.com/posts \"forex\" \"best broker\" {region}",
  "site:linkedin.com/posts \"forex\" \"partnership\" \"broker\" {region}",
  "site:linkedin.com/posts \"forex\" \"affiliate\" \"partner\" {region}",
  "site:linkedin.com/feed/update \"forex\" \"looking for broker\" {region}",
  "site:linkedin.com/feed/update \"forex\" \"broker recommendation\" {region}",
  "site:instagram.com \"forex trader\" \"whatsapp\" {region}",
  "site:instagram.com \"forex mentor\" \"whatsapp\" {region}",
  "site:instagram.com \"forex signals\" \"whatsapp\" {region}",
  "site:instagram.com \"trading academy\" \"forex\" {region}",
  "site:instagram.com \"forex\" \"linktr.ee\" {region}",
  "site:instagram.com \"forex\" \"beacons\" {region}",
  "site:instagram.com \"forex\" \"telegram\" {region}",
  "site:instagram.com/p \"forex\" \"broker\" {region}",
  "site:instagram.com/p \"forex\" \"corretora\" Brasil",
  "site:instagram.com/p \"forex\" \"broker\" LatAm",
  "site:x.com \"forex\" \"looking for broker\"",
  "site:x.com \"forex\" \"recommend broker\"",
  "site:x.com \"forex\" \"best broker\"",
  "site:x.com \"forex\" \"IB partner\"",
  "site:x.com \"forex\" \"affiliate\" \"broker\"",
  "site:x.com \"forex\" \"trading community\"",
  "\"forex signals\" \"x.com\"",
  "\"forex affiliate\" \"x.com\"",
  "\"introducing broker\" \"x.com\" forex",
  "\"forex broker\" \"x.com\" \"recommend\"",
  "\"xauusd\" \"x.com\" \"trader\"",
  "site:twitter.com \"forex\" \"looking for broker\"",
  "site:twitter.com \"forex\" \"recommend broker\"",
  "site:facebook.com \"forex\" \"whatsapp\" \"broker\" {region}",
  "site:facebook.com \"forex trading\" \"community\" \"whatsapp\" {region}",
  "site:facebook.com/groups \"forex\" \"trading\" {region}",
  "site:tiktok.com \"forex trader\" {region}",
  "site:tiktok.com \"forex signals\" {region}",
  "site:threads.net \"forex\" \"broker\"",
  "site:linktr.ee \"forex trader\" {region}",
  "site:beacons.ai \"forex trader\" {region}",
  "site:allmylinks.com \"forex trader\" {region}",
  "site:linkedin.com/in \"forex\" \"introducing broker\" \"contact\" {region}",
  "site:linkedin.com/in \"forex\" \"IB\" \"partner\" {region}",
  "site:linkedin.com/in \"forex\" \"affiliate\" \"CPA\" {region}",
  "site:linkedin.com/in \"forex\" \"revenue share\" {region}",
  "site:linkedin.com/in \"XAUUSD\" \"trader\" {region}",
  "site:linkedin.com/in \"copy trading\" \"forex\" {region}",
  "site:linkedin.com/in \"PAMM\" \"forex\" {region}",
  "site:linkedin.com/in \"MAM\" \"forex\" {region}",
  "site:linkedin.com/in \"trading community\" \"founder\" {region}",
  "site:linkedin.com/in \"forex academy\" \"founder\" {region}",
  "site:linkedin.com/in \"forex signals\" \"founder\" {region}",
  "site:linkedin.com/in \"telegram\" \"forex\" \"founder\" {region}",
  "site:linkedin.com/in \"discord\" \"forex\" \"community\" {region}",
  "site:linkedin.com/in \"investment adviser\" \"forex\" {region}",
  "site:linkedin.com/in \"fund manager\" \"forex\" {region}",
  "site:linkedin.com/in \"portfolio manager\" \"XAUUSD\" {region}",
  "site:linkedin.com/company \"forex academy\" {region}",
  "site:linkedin.com/company \"trading education\" \"forex\" {region}",
  "site:linkedin.com/company \"forex signals\" {region}",
  "site:linkedin.com/company \"forex community\" {region}",
  "site:linkedin.com/posts \"forex\" \"introducing broker\" {region}",
  "site:linkedin.com/posts \"forex\" \"IB\" \"commission\" {region}",
  "site:linkedin.com/posts \"forex\" \"CPA\" \"affiliate\" {region}",
  "site:linkedin.com/posts \"forex\" \"revenue share\" {region}",
  "site:linkedin.com/posts \"forex\" \"looking for broker\" {region}",
  "site:linkedin.com/posts \"XAUUSD\" \"signals\" {region}",
  "site:instagram.com \"forex\" \"linktr.ee\" \"whatsapp\" {region}",
  "site:instagram.com \"forex\" \"beacons.ai\" \"whatsapp\" {region}",
  "site:instagram.com \"forex\" \"telegram\" \"whatsapp\" {region}",
  "site:instagram.com \"xauusd\" \"whatsapp\" {region}",
  "site:instagram.com \"gold trader\" \"telegram\" {region}",
  "site:instagram.com \"forex academy\" \"whatsapp\" {region}",
  "site:instagram.com \"trading mentor\" \"forex\" {region}",
  "site:instagram.com/reel \"forex\" \"broker\" {region}",
  "site:instagram.com/p \"forex\" \"introducing broker\" {region}",
  "site:x.com \"forex\" \"introducing broker\"",
  "site:x.com \"forex\" \"affiliate\" \"CPA\"",
  "site:x.com \"forex\" \"revenue share\"",
  "site:x.com \"xauusd\" \"signals\"",
  "site:x.com \"gold trader\" \"telegram\"",
  "site:x.com \"forex\" \"whatsapp\" \"signals\"",
  "site:twitter.com \"forex\" \"introducing broker\"",
  "site:twitter.com \"xauusd\" \"signals\"",
  "site:tiktok.com/@ \"forex trader\" {region}",
  "site:tiktok.com/@ \"xauusd\" \"trader\" {region}",
  "site:tiktok.com/@ \"forex signals\" {region}",
  "site:tiktok.com/@ \"trading academy\" \"forex\" {region}",
  "\"forex trader\" \"tiktok.com/@\" {region}",
  "\"xauusd\" \"tiktok.com/@\" \"trader\"",
  "\"forex signals\" \"tiktok.com/@\"",
  "site:t.me \"forex\" \"IB\"",
  "site:t.me \"forex\" \"affiliate\"",
  "site:t.me \"xauusd\" \"signals\"",
  "site:t.me \"forex\" \"copy trading\"",
  "site:t.me/s \"forex\" \"signals\"",
  "site:t.me/s \"xauusd\"",
  "site:discord.gg \"forex\" \"trading\"",
  "site:discord.gg \"xauusd\"",
  "site:disboard.org/server \"forex\" \"trading\"",
  "site:disboard.org/server \"xauusd\"",
  "site:discord.com/invite \"forex trading\""
];

export const FORUM_QUERY_TEMPLATES = [
  "site:reddit.com/r/Forex \"which broker\"",
  "site:reddit.com/r/Forex \"recommend broker\"",
  "site:reddit.com/r/Forex \"best broker\"",
  "site:reddit.com/r/Forex \"looking for broker\"",
  "site:reddit.com/r/Forex \"introducing broker\"",
  "site:reddit.com/r/Daytrading \"forex broker\"",
  "site:reddit.com/r/Daytrading \"which broker\"",
  "site:reddit.com/r/Trading \"forex broker\"",
  "site:reddit.com/r/algotrading \"forex broker\"",
  "site:reddit.com/r/Forex \"prop firm\"",
  "site:tradingview.com/u/ \"forex\" \"signals\"",
  "site:tradingview.com/u/ \"forex\" \"broker\"",
  "site:tradingview.com/ideas \"forex\" \"broker\"",
  "site:tradingview.com/ideas \"forex\" \"community\"",
  "site:forexfactory.com/thread \"broker\" \"forex\"",
  "site:forexfactory.com/thread \"which broker\"",
  "site:forexfactory.com/thread \"introducing broker\"",
  "site:forexfactory.com \"forex\" \"telegram\"",
  "site:forums.babypips.com \"which broker\"",
  "site:forums.babypips.com \"recommend broker\"",
  "site:forums.babypips.com \"forex broker\"",
  "\"forex forum\" \"which broker\"",
  "\"forex forum\" \"recommend broker\"",
  "\"forex forum\" \"introducing broker\"",
  "\"forex trading forum\" \"affiliate\" \"broker\"",
  "\"forex community\" \"forum\" \"broker\""
];

export const SPECIALIST_QUERY_TEMPLATES = [
  "site:myfxbook.com/members \"forex\" \"manager\"",
  "site:myfxbook.com/members \"XAUUSD\"",
  "site:myfxbook.com/portfolio \"forex\" \"public\"",
  "site:myfxbook.com/members \"gold\" \"forex\"",
  "site:myfxbook.com/members \"copy trading\"",
  "site:myfxbook.com/portfolio \"XAUUSD\" \"public\"",
  "site:myfxbook.com/portfolio \"forex\" \"gain\"",
  "site:myfxbook.com/portfolio \"forex\" \"drawdown\"",
  "site:myfxbook.com/reviews/brokers \"introducing broker\"",
  "site:myfxbook.com/community \"broker\" \"forex\"",
  "site:myfxbook.com/community \"copy trading\" \"forex\"",
  "site:myfxbook.com/community \"which broker\" \"forex\"",
  "site:myfxbook.com/community \"IB\" \"forex\"",
  "site:mql5.com/en/signals \"forex\" \"growth\"",
  "site:mql5.com/en/signals \"XAUUSD\"",
  "site:mql5.com/en/signals \"gold\" \"growth\"",
  "site:mql5.com/en/signals \"forex\" \"subscribers\"",
  "site:mql5.com/en/market \"forex\" \"signal\"",
  "site:mql5.com/en/users \"forex\" \"signals\"",
  "site:mql5.com/en/users \"copy trading\"",
  "site:mql5.com/en/users \"XAUUSD\"",
  "site:mql5.com/en/users \"PAMM\"",
  "site:mql5.com/en/forum \"broker\" \"forex\"",
  "site:mql5.com/en/forum \"introducing broker\"",
  "site:mql5.com/en/forum \"PAMM\" \"forex\"",
  "site:mql5.com/en/forum \"which broker\" \"forex\"",
  "site:mql5.com/en/forum \"affiliate\" \"forex\"",
  "site:fxblue.com/users \"forex\"",
  "site:fxblue.com/users \"XAUUSD\"",
  "site:fxblue.com/users \"gold\"",
  "site:zulutrade.com/trader \"forex\"",
  "site:zulutrade.com/trader \"gold\"",
  "site:darwinex.com/darwin \"forex\"",
  "site:darwinex.com/darwin \"xauusd\"",
  "site:signalstart.com/analysis \"forex\"",
  "site:signalstart.com/analysis \"xauusd\"",
  "site:collective2.com \"forex\" \"strategy\"",
  "site:collective2.com \"xauusd\"",
  "site:forexpeacearmy.com/community \"which broker\"",
  "site:forexpeacearmy.com/community \"introducing broker\"",
  "site:earnforex.com/forum \"which broker\"",
  "site:earnforex.com/forum \"introducing broker\"",
  "site:forex-station.com \"XAUUSD\" \"indicator\"",
  "site:forex-station.com \"broker\" \"forex\"",
  "site:trade2win.com \"forex broker\"",
  "site:elitetrader.com \"forex broker\"",
  "\"PAMM manager\" \"forex\" {region}",
  "\"MAM account manager\" \"forex\" {region}",
  "\"money manager\" \"forex\" {region}",
  "\"forex money manager\" \"contact\" {region}",
  "\"copy trading provider\" \"forex\" {region}",
  "\"signal seller\" \"forex\" \"telegram\" {region}",
  "\"XAUUSD\" \"signals\" \"whatsapp\" {region}",
  "\"gold trader\" \"XAUUSD\" \"telegram\" {region}",
  "\"CPA deal\" \"forex\" \"affiliate\"",
  "\"CPA forex\" \"affiliate\" \"IB\"",
  "\"revenue share\" \"forex\" \"affiliate\"",
  "\"introducing broker\" \"CPA\" \"forex\"",
  "\"IB program\" \"forex\" \"telegram\"",
  "site:adviserinfo.sec.gov \"foreign exchange\" \"investment adviser\"",
  "site:sec.gov \"foreign exchange\" \"investment adviser\"",
  "site:fca.org.uk \"foreign exchange\" \"investment adviser\"",
  "site:register.fca.org.uk \"foreign exchange\" \"asset management\"",
  "site:cvm.gov.br \"consultor de valores mobiliarios\" \"derivativos\"",
  "site:cadastro.cvm.gov.br \"consultor\" \"derivativos\"",
  "site:cnmv.es \"divisas\" \"gestora\"",
  "site:cmfchile.cl \"asesor\" \"inversiones\" \"divisas\"",
  "site:superfinanciera.gov.co \"asesor\" \"forex\""
];

export const ECOSYSTEM_QUERY_TEMPLATES = [
  "\"forex expo\" \"exhibitors\" {region}",
  "\"forex expo\" \"sponsors\" {region}",
  "\"forex expo\" \"speakers\" {region}",
  "\"trading expo\" \"exhibitors\" {region}",
  "\"trading expo\" \"sponsors\" {region}",
  "\"trading summit\" \"forex\" \"sponsors\" {region}",
  "\"money expo\" \"forex\" \"exhibitors\" {region}",
  "\"money expo\" \"trading\" \"speakers\" {region}",
  "\"traders fair\" \"forex\" \"exhibitors\" {region}",
  "\"traders fair\" \"speakers\" \"forex\" {region}",
  "\"finance magnates\" \"forex\" \"speakers\" {region}",
  "\"iFX EXPO\" \"exhibitors\" \"forex\"",
  "\"iFX EXPO\" \"sponsors\" \"partners\"",
  "\"Forex Expo Dubai\" \"exhibitors\"",
  "\"Forex Expo Dubai\" \"speakers\"",
  "\"Wiki Finance Expo\" \"forex\" \"exhibitors\"",
  "\"Smart Vision Investment Expo\" \"forex\"",
  "\"Expo Trading\" \"forex\" \"LatAm\"",
  "\"Money Expo Colombia\" \"forex\"",
  "\"Money Expo Mexico\" \"trading\"",
  "\"Traders Fair\" \"Latin America\" \"forex\"",
  "site:ifxexpo.com \"exhibitors\" \"forex\"",
  "site:forexexpo.com \"exhibitors\"",
  "site:moneyexpo.com \"forex\" \"exhibitors\"",
  "site:tradersfair.com \"forex\" \"exhibitors\"",
  "site:financemagnates.com \"forex\" \"summit\" \"speakers\"",
  "site:events.financemagnates.com \"forex\" \"sponsors\"",
  "site:linkedin.com/in \"attended\" \"forex expo\" {region}",
  "site:linkedin.com/in \"speaker\" \"forex expo\" {region}",
  "site:linkedin.com/in \"sponsor\" \"trading expo\" {region}",
  "site:linkedin.com/posts \"forex expo\" \"sponsor\" {region}",
  "site:linkedin.com/posts \"trading expo\" \"speaker\" {region}",
  "\"asset management\" \"forex\" {region}",
  "\"wealth management\" \"forex\" {region}",
  "\"family office\" \"forex\" {region}",
  "\"investment fund\" \"forex\" {region}",
  "\"fund manager\" \"forex\" {region}",
  "\"portfolio manager\" \"forex\" {region}",
  "\"hedge fund\" \"forex\" {region}",
  "\"investment club\" \"forex\" {region}",
  "\"clube de investimento\" \"forex\" Brasil",
  "\"gestora de recursos\" \"forex\" Brasil",
  "\"gestor de investimentos\" \"forex\" Brasil",
  "\"consultor de valores mobiliarios\" \"forex\" Brasil",
  "\"asesor financiero\" \"forex\" LatAm",
  "\"gestor de fondos\" \"forex\" LatAm",
  "\"administradora de fondos\" \"forex\" LatAm",
  "site:linkedin.com/company \"asset management\" \"forex\" {region}",
  "site:linkedin.com/company \"wealth management\" \"forex\" {region}",
  "site:linkedin.com/in \"portfolio manager\" \"forex\" {region}",
  "site:linkedin.com/in \"fund manager\" \"forex\" {region}",
  "site:linkedin.com/in \"wealth manager\" \"forex\" {region}",
  "site:cvm.gov.br \"gestor\" \"investimentos\" \"forex\"",
  "site:cadastro.cvm.gov.br \"consultor\" \"investimentos\"",
  "site:anbima.com.br \"gestor\" \"fundos\" \"investimentos\"",
  "site:sec.gov \"investment adviser\" \"forex\"",
  "site:adviserinfo.sec.gov \"forex\" \"investment adviser\"",
  "site:adviserinfo.sec.gov \"foreign exchange\" \"investment adviser\"",
  "site:adviserinfo.sec.gov \"currency\" \"investment adviser\"",
  "site:sec.gov \"Form ADV\" \"foreign exchange\"",
  "site:sec.gov \"Form ADV\" \"currency trading\"",
  "site:fca.org.uk \"forex\" \"asset management\"",
  "site:register.fca.org.uk \"forex\" \"investment\"",
  "site:register.fca.org.uk \"foreign exchange\" \"investment\"",
  "site:register.fca.org.uk \"contract for difference\" \"investment\"",
  "site:cnmv.es \"forex\" \"gestora\"",
  "site:cnmv.es \"divisas\" \"gestora\"",
  "site:cnmv.es \"asesor financiero\" \"divisas\"",
  "site:cmfchile.cl \"forex\" \"administradora\"",
  "site:cmfchile.cl \"asesor\" \"inversiones\" \"divisas\"",
  "site:cmfchile.cl \"administradora general de fondos\" \"divisas\"",
  "site:superfinanciera.gov.co \"forex\" \"comisionista\"",
  "site:superfinanciera.gov.co \"asesor\" \"forex\"",
  "site:superfinanciera.gov.co \"divisas\" \"asesor\"",
  "site:cvm.gov.br \"consultor de valores mobiliarios\" \"derivativos\"",
  "site:cadastro.cvm.gov.br \"consultor\" \"derivativos\"",
  "site:cadastro.cvm.gov.br \"gestor\" \"fundos\"",
  "site:gov.br/cvm \"consultor\" \"derivativos\"",
  "site:anbima.com.br \"gestor\" \"fundos\" \"derivativos\"",
  "site:asic.gov.au \"foreign exchange\" \"financial adviser\"",
  "site:moneysmart.gov.au \"foreign exchange\" \"financial adviser\"",
  "site:mas.gov.sg \"foreign exchange\" \"fund manager\"",
  "site:sfc.hk \"foreign exchange\" \"asset management\"",
  "site:dfsa.ae \"investment adviser\" \"forex\"",
  "site:adgm.com \"fund manager\" \"forex\"",
  "site:opencorporates.com \"forex\" \"trading\" \"director\"",
  "site:opencorporates.com \"foreign exchange\" \"director\"",
  "site:opencorporates.com \"trading academy\" \"director\"",
  "site:find-and-update.company-information.service.gov.uk \"forex\" \"director\"",
  "site:find-and-update.company-information.service.gov.uk \"trading academy\" \"director\"",
  "site:companieshouse.gov.uk \"foreign exchange\" \"director\"",
  "site:empresite.eleconomistaamerica.co \"forex\" \"representante\"",
  "site:empresite.eleconomistaamerica.co \"trading\" \"representante\"",
  "\"forex\" \"company registration\" \"director\" {region}",
  "\"trading academy\" \"company registration\" \"director\" {region}",
  "\"forex\" \"shareholder\" \"director\" \"company\" {region}",
  "\"foreign exchange\" \"beneficial owner\" \"company\"",
  "\"prop trading firm\" \"forex\" {region}",
  "\"prop firm\" \"forex\" \"community\" {region}",
  "\"funded trader\" \"forex\" {region}",
  "\"funded trading\" \"forex\" {region}",
  "\"trading desk\" \"forex\" {region}",
  "\"proprietary trading\" \"forex\" {region}",
  "\"copy trading provider\" \"forex\" {region}",
  "\"PAMM\" \"forex\" \"manager\" {region}",
  "\"MAM account\" \"forex\" \"manager\" {region}",
  "\"signal provider\" \"forex\" \"whatsapp\" {region}",
  "\"forex academy\" \"partnership\" {region}",
  "\"trading academy\" \"sponsor\" \"broker\" {region}",
  "\"trading school\" \"forex\" \"contact\" {region}",
  "\"educacion financiera\" \"forex\" \"comunidad\" {region}",
  "\"educacao financeira\" \"forex\" \"comunidade\" Brasil",
  "site:hotmart.com \"forex\" \"curso\" Brasil",
  "site:kiwify.com.br \"forex\" \"curso\"",
  "site:eduzz.com \"forex\" \"curso\"",
  "site:udemy.com \"forex\" \"Portuguese\"",
  "site:udemy.com \"forex\" \"Spanish\"",
  "\"forex meetup\" {region}",
  "site:meetup.com \"forex trading\" {region}",
  "\"telegram\" \"forex\" \"admin\" {region}",
  "\"discord\" \"forex\" \"community manager\" {region}",
  "\"forex community\" \"sponsor\" {region}",
  "\"retail trading community\" \"sponsor\" {region}",
  "\"fintech\" \"forex\" \"partnership\" {region}",
  "\"payments\" \"forex\" \"traders\" {region}",
  "\"crypto community\" \"forex\" \"trading\" {region}",
  "\"latam fintech\" \"forex\" \"trading\"",
  "\"corretora\" \"parceria\" \"academia de trading\" Brasil",
  "\"broker\" \"partnership\" \"trading academy\" LatAm",
  "\"forex\" \"expo\" \"attendees\"",
  "\"forex\" \"conference\" \"attendees\"",
  "\"trading\" \"conference\" \"sponsors\" \"forex\""
];

export const SEARCH_ENGINES = ["yahoo", "bing-rss", "bing", "brave-html"];

export const PAGE_FETCH_DENYLIST = [
  "linkedin.com",
  "facebook.com",
  "instagram.com",
  "x.com",
  "twitter.com",
  "tiktok.com",
  "youtube.com",
  "reddit.com",
  "telegram.me",
  "t.me"
];
